
---
title: "data_cleaning"
output: pdf_document
date: "2024-10-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{R}
library(readr)
library(tidyverse)
library(stringr)
library(ggplot2)

```

```{R import}
set.seed(123)

players_20_raw <- read_csv("../data/raw_data/players_20.csv")
players_20_raw <- players_20_raw %>% filter(player_positions != "GK")

rows_to_keep <- floor(0.3 * nrow(players_20_raw))
sampled_rows <- sample(1:nrow(players_20_raw), size = rows_to_keep)
player_20_reduced <- players_20_raw[sampled_rows, ]


players_20 <- player_20_reduced |> select(
  short_name,
  age,
  height_cm,
  weight_kg, 
  nationality,
  club,
  overall,
  potential,
  value_eur,
  wage_eur,
  player_positions,
  international_reputation,
  skill_moves,
  body_type,
  release_clause_eur,
  player_tags,
  team_position,
  pace,
  shooting,
  passing,
  dribbling,
  defending,
  physic
)
summary(players_20)

```


```{R}
players_20$Top_country <- ifelse(players_20$nationality %in% c("Belgium", "France", "Brazil","England","Portugal","Spain","Argentina","Uruguay","Mexico"), 
                        "Top_9", 
                        ifelse(players_20$nationality %in% c("Italy", "Croatia","Denmark","Germany","Netherlands","Colombia","Switzerland","Chile","Wales","Poland","Senegal","Sweden"), 
                               "Top_20", 
                               "Other"))


players_20 <- players_20 %>%
  mutate(
    Top_Club = case_when(
      club %in% c(
        "FC Bayern München", "Real Madrid", "FC Barcelona", "Atlético Madrid",
        "Juventus", "Manchester City", "Paris Saint-Germain", "Sevilla FC",
        "Manchester United", "Liverpool"
      ) ~ "Top_10",
      club %in% c(
        "Arsenal", "Shakhtar Donetsk", "Borussia Dortmund", "Tottenham Hotspur",
        "Olympique Lyonnais", "Chelsea", "Roma", "Napoli", "FC Porto", "SL Benfica"
      ) ~ "Top_20",
      club %in% c(
        "Ajax", "Bayer 04 Leverkusen", "FC Basel 1893", "Villarreal CF",
        "Dynamo Kyiv", "Valencia CF", "Beşiktaş JK", "FC Red Bull Salzburg",
        "Sporting CP", "RB Leipzig"
      ) ~ "Top_30",
      TRUE ~ "other"
    )
  )
players_20 <- players_20 %>%
  mutate(
    is_sub = case_when(
      team_position %in% c('SUB', 'RES') ~ 1,
      TRUE ~ 0
    )
  )
players_20$release_clause_eur[is.na(players_20$release_clause_eur)] <- 0

```


```{R}

players_20$number_tags_proc <- str_count(players_20$player_tags, ",")
players_20$number_tags <- ifelse(players_20$number_tags_proc == 0,0,players_20$number_tags_proc + 1)

players_20$number_tags_proc <- NULL

players_20$number_tags[is.na(players_20$number_tags)] <- 0
players_20$player_positions <- sub(",.*","",players_20$player_positions)

```

```{R}
players_20
```


###overall try fit
```{R}

fit_rating = lm(overall ~ age + wage_eur +international_reputation + is_sub 
                          + Top_Club + value_eur+ height_cm + weight_kg + release_clause_eur
                          , data = players_20)

```

```{R}
fitted_value = fitted(fit_rating)

plot(fitted_value,players_20$overall, xlim=c(50,100))
abline(0, 1, col='blue')
residual = resid(fit_rating)
plot(fitted_value, residual, xlim=c(50, 85))
plot(fit_rating, which = 2)
```

###Write as csv file in data/cleaned_data
```{r}
final_data <- players_20 |> select(overall, age, wage_eur, international_reputation, is_sub 
                          , Top_Club, value_eur, height_cm, weight_kg, release_clause_eur)
write.csv(final_data, "../data/cleaned_data/cleaned_data.csv")
data <- read.csv("../data/cleaned_data/cleaned_data.csv")
transform_data <- data
summary_stats <- data.frame(
  min = min(data$overall),
  max = max(data$overall),
  mean = mean(data$overall),
  median = median(data$overall),
  standard_deviation = sd(data$overall)
)
data

```

###Some baisc assumption check
```{R}
plot(data[, c(2,3,4,5,6)], main="Response against predictor first 4")

plot(data[, c(2,7,8,9,10,11)], main="Response against predictor other")
```
###box cox for each varibles
```{R}
library(MASS)

boxcox_fit <- boxcox(fit_rating, lambda = seq(-2, 2, 0.1))  
optimal_lambda <- boxcox_fit$x[which.max(boxcox_fit$y)]
cat("Optimal lambda:", optimal_lambda, "\n")


fit_age <- lm(overall ~ age, data = players_20)
boxcox_fit <- boxcox(fit_age, lambda = seq(-2, 2, 0.1))
optimal_lambda_age <- boxcox_fit$x[which.max(boxcox_fit$y)]
cat("Optimal lambda for age:", optimal_lambda_age, "\n")

fit_value <-  lm(overall ~ value_eur, data = players_20)
boxcox_fit_1 <- boxcox(fit_value, lambda = seq(-2, 2, 0.1))
optimal_lambda_value <- boxcox_fit_1$x[which.max(boxcox_fit_1$y)]
cat("Optimal lambda for value_eur:", optimal_lambda_value, "\n")

fit_release <-lm(overall ~ release_clause_eur, data = players_20)
boxcox_fit <- boxcox(fit_release, lambda = seq(-2, 2, 0.1))
optimal_lambda_age <- boxcox_fit$x[which.max(boxcox_fit$y)]
cat("Optimal lambda for release_clause_eur:", optimal_lambda_age, "\n")

fit_height <-lm(overall ~ height_cm, data = players_20)
boxcox_fit <- boxcox(fit_height, lambda = seq(-2, 2, 0.1))
optimal_lambda_age <- boxcox_fit$x[which.max(boxcox_fit$y)]
cat("Optimal lambda for height_cm:", optimal_lambda_age, "\n")

fit_weight <-lm(overall ~ weight_kg , data = players_20)
boxcox_fit <- boxcox(fit_weight, lambda = seq(-2, 2, 0.1))
optimal_lambda_age <- boxcox_fit$x[which.max(boxcox_fit$y)]
cat("Optimal lambda for weight_kg:", optimal_lambda_age, "\n")

fit_wage_eur <-lm(overall ~ wage_eur , data = players_20)
boxcox_fit <- boxcox(fit_wage_eur, lambda = seq(-2, 2, 0.1))
optimal_lambda_age <- boxcox_fit$x[which.max(boxcox_fit$y)]
cat("Optimal lambda for wage_eur:", optimal_lambda_age, "\n")

detach("package:MASS", unload = TRUE)
```
###trying some fit on overall
```{R}
players_20$overall_transformed <- (players_20$overall)^2
fit_rating_tran_over = lm(overall_transformed  ~ age + wage_eur +international_reputation + is_sub 
                          + Top_Club + value_eur+ height_cm + weight_kg + release_clause_eur
                          , data = players_20)
fitted_value_1 = fitted(fit_rating_tran_over)
plot(fitted_value_1,players_20$overall_transformed)
abline(0, 1, col='blue')
residual = resid(fit_rating_tran_over)
plot(fitted_value_1, residual)
plot(fit_rating_tran_over, which = 2)
```
###trying some fit on predictor
```{R}
players_20$age_tran <- (players_20$age^0.4646465  - 1) / 0.4646465 
players_20$value_tran <- (players_20$value_eur)^2
players_20$release_tran <- (players_20$release_clause_eur)^2
players_20$wage_tran <- (players_20$wage_eur)^2

fit_rating_tran = lm(overall  ~ age_tran + wage_tran +international_reputation + is_sub 
                          + Top_Club + value_tran + release_tran
                          , data = players_20)
fitted_value_better = fitted(fit_rating_tran)
plot(fitted_value_better,players_20$overall, xlim=c(50,100))
abline(0, 1, col='blue')
residual = resid(fit_rating_tran)
plot(fitted_value_better, residual, xlim=c(50,100))
plot(fit_rating_tran, which = 2)

```
###final transformation
```{R}
library(MASS)
fit_rating_tran = lm(overall  ~ age_tran + wage_tran +international_reputation + is_sub 
                          + Top_Club + value_tran + release_tran
                          , data = players_20)
boxcox_fit <- boxcox(fit_rating_tran, lambda = seq(-1000, 1000, 0.1))  
optimal_lambda <- boxcox_fit$x[which.max(boxcox_fit$y)]
cat("Optimal lambda:", optimal_lambda, "\n")
detach("package:MASS", unload = TRUE)
```
###final transformation result
```{R}
players_20$overall_transformed <- (players_20$overall)^2.4

fit_rating_tran = lm(overall_transformed  ~ age_tran + wage_tran +international_reputation + is_sub 
                          + Top_Club + value_tran + release_tran
                          , data = players_20)
fitted_value_better = fitted(fit_rating_tran)
plot(fitted_value_better,players_20$overall_transformed)
abline(0, 1, col='blue')
residual = resid(fit_rating_tran)
plot(fitted_value_better, residual)
plot(fit_rating_tran, which = 2)

```
###data after tranformation
```{R}
transformated_data <- players_20 |> select(overall_transformed, age_tran,wage_tran,international_reputation, is_sub , Top_Club , value_tran ,release_tran)

write.csv(transformated_data, "../data/cleaned_data/transformated_data.csv")
data <- read.csv("../data/cleaned_data/transformated_data.csv")

summary(data)
```


###interation here !!!!! not done !!!!
```{R}
plot(data[, c(2,3,4,5,6,7,8,9)], main="Response against predictor first 4")


fit_rating_final= lm(overall  ~ age_tran + wage_tran +international_reputation + is_sub 
                          + Top_Club + value_tran + release_tran + value_tran:release_tran + age_tran:value_tran
                     + value_tran:wage_tran
                          , data = players_20)

fitted_value_better = fitted(fit_rating_final)
plot(fitted_value_better,players_20$overall_transformed)
abline(0, 1, col='blue')
residual = resid(fit_rating_final)
plot(fitted_value_better, residual)
plot(fit_rating_final, which = 2)
 
```

###t test now !!!
```{R}
 fit_rating_final= lm(overall  ~ age_tran + wage_tran +international_reputation + is_sub 
                          + Top_Club + value_tran + release_tran + value_tran:release_tran + age_tran:value_tran
                     + value_tran:wage_tran
                          , data = players_20)
summary(fit_rating_final)

```


###anova
```{R}
 fit_rating_final= lm(overall  ~ age_tran + wage_tran +international_reputation + is_sub 
                          + Top_Club + value_tran + release_tran + value_tran:release_tran + age_tran:value_tran
                     + value_tran:wage_tran
                          , data = players_20)
anova_table <- anova(fit_rating_final)

print(anova_table)
```

###CI
```{R}
 fit_rating_final= lm(overall  ~ age_tran + wage_tran +international_reputation + is_sub 
                          + Top_Club + value_tran + release_tran + value_tran:release_tran + age_tran:value_tran
                     + value_tran:wage_tran
                          , data = players_20)
confint(fit_rating_final, level = 0.95)
confint(fit_rating_final, level = 0.975)

coef_estimates <- coef(fit_rating_final)
std_errors <- summary(fit_rating_final)$coefficients[, "Std. Error"]

t_critical <- qt(0.975, df = df.residual(fit_rating_final))

lower_bound <- coef_estimates - t_critical * std_errors
upper_bound <- coef_estimates + t_critical * std_errors

confidence_intervals <- data.frame(
  Estimate = coef_estimates,
  Lower = lower_bound,
  Upper = upper_bound
)

confidence_intervals


```
###PI
```{R}
fit_rating_final= lm(overall  ~ age_tran + wage_tran +international_reputation + is_sub 
                          + Top_Club + value_tran + release_tran
                          , data = players_20)
predict(fit_rating_final, level = 0.95)
predict(fit_rating_final, level = 0.975)

coef_estimates <- coef(fit_rating_final)
std_errors <- summary(fit_rating_final)$coefficients[, "Std. Error"]


```
###VIF multicollinearity

```{R}
install.packages("car")
library("car")


fit_rating_final= lm(overall  ~ age_tran + wage_tran +international_reputation + is_sub 
                          + Top_Club + value_tran + release_tran + value_tran:release_tran + age_tran:value_tran
                     + value_tran:wage_tran
                          , data = players_20)

vif(fit_rating_final)

```
### Drop release
```{R}
fit_rating_final= lm(overall  ~ age_tran + international_reputation + is_sub 
                          + Top_Club + value_tran + wage_tran + age_tran:value_tran
                     + value_tran:wage_tran
                          , data = players_20)

summary(fit_rating_final)
```
```{R}
# Check the full model assumptions
par ( mfrow = c (2 , 2) )
plot ( fit_rating_final , which = c (1 , 2 , 3 , 4) )
reduced_fit = step ( fit_rating_final , direction = "backward" , k = 2)
summary ( reduced_fit )
# Check the final model assumptions
par ( mfrow = c (2 , 2) )
plot ( reduced_fit , which = c (1 , 2 , 3 , 4) )

```
```{R}
cooks_dist <- cooks.distance(reduced_fit)
plot(cooks_dist, type = "h", main = "Cook's Distance", ylab = "Cook's Distance")
abline(h = 4 / length(cooks_dist), col = "red", lty = 2)

influential_points <- which(cooks_dist > 4 / length(cooks_dist))
print(players_20[1452, ])
print(influential_points)
cleaned_data <- players_20[-influential_points, ]
fit_after_cooks= lm(overall  ~ age_tran + international_reputation + is_sub 
                          + Top_Club + value_tran + wage_tran + age_tran:value_tran
                     + value_tran:wage_tran
                          , data = cleaned_data)

par ( mfrow = c (2 , 2) )
plot ( fit_after_cooks , which = c (1 , 2 , 3 , 4) )
summary(fit_after_cooks)
```

```{R}
summary(fit_after_cooks)

```